"""
report.py
Module 9: Report Generation (Page 6)
Generates a downloadable HTML report and a lightweight PDF summary.
"""

import io
import datetime
import streamlit as st
import pandas as pd
from fpdf import FPDF

from src.utils import safe_round
from src.theme import module_header


def _build_html_report():
    df = st.session_state["df"]
    dataset_name = st.session_state.get("dataset_name", "Unknown")
    objective = st.session_state.get("analysis_objective", "N/A")
    normality_df = st.session_state.get("normality_results", pd.DataFrame())
    homogeneity = st.session_state.get("homogeneity_results")
    recommendation = st.session_state.get("test_recommendation", {})
    result = st.session_state.get("test_results", {})
    posthoc = st.session_state.get("posthoc_results")
    interp = st.session_state.get("interpretation", {})

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    homogeneity_html = "<p>Not applicable for this analysis objective.</p>"
    if homogeneity and homogeneity.get("p_value") is not None:
        homogeneity_html = (
            f"<p><b>Levene's Test p-value:</b> {safe_round(homogeneity.get('p_value'))} "
            f"— Equal variance assumption: {'Satisfied' if homogeneity.get('equal_variance') else 'Violated'}</p>"
        )

    posthoc_html = ""
    if posthoc is not None:
        posthoc_html = f"<h3>Post-Hoc Analysis — {posthoc['method']}</h3>" + posthoc["table"].to_html(index=False)

    html = f"""
    <html>
    <head>
        <meta charset="utf-8">
        <title>SIP Statistical Analysis Report</title>
        <style>
            body {{ font-family: Arial, Helvetica, sans-serif; margin: 40px; color: #1a1a1a; }}
            h1 {{ color: #0B3D91; border-bottom: 3px solid #0B3D91; padding-bottom: 8px; }}
            h2 {{ color: #0B3D91; margin-top: 32px; }}
            table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
            th, td {{ border: 1px solid #ccc; padding: 6px 10px; text-align: left; font-size: 14px; }}
            th {{ background-color: #0B3D91; color: white; }}
            .badge {{ display: inline-block; padding: 4px 10px; border-radius: 4px; font-weight: bold; }}
            .footer {{ margin-top: 40px; font-size: 12px; color: #888; }}
        </style>
    </head>
    <body>
        <h1>📊 Statistical Intelligence Platform — Analysis Report</h1>
        <p><b>Generated:</b> {now}</p>

        <h2>1. Dataset Information</h2>
        <p><b>Dataset Name:</b> {dataset_name}</p>
        <p><b>Rows:</b> {df.shape[0]:,} &nbsp;|&nbsp; <b>Columns:</b> {df.shape[1]:,}</p>

        <h2>2. Analysis Objective & Selected Variables</h2>
        <p><b>Objective:</b> {objective}</p>
        <p><b>Group Variable:</b> {st.session_state.get('group_col', 'N/A')} &nbsp;|&nbsp;
           <b>Value Variable:</b> {st.session_state.get('value_col', 'N/A')} &nbsp;|&nbsp;
           <b>Secondary Variable:</b> {st.session_state.get('value_col_2', 'N/A')}</p>

        <h2>3. Assumption Test Results</h2>
        <h3>Normality</h3>
        {normality_df.to_html(index=False) if not normality_df.empty else '<p>No normality results available.</p>'}
        <h3>Homogeneity of Variance</h3>
        {homogeneity_html}

        <h2>4. Selected Statistical Method</h2>
        <p><b>Recommended:</b> {recommendation.get('test', 'N/A')}</p>
        <ul>{''.join(f'<li>{r}</li>' for r in recommendation.get('reasoning', []))}</ul>
        <p><b>Test Actually Run:</b> {result.get('test', 'N/A')}</p>

        <h2>5. Statistical Output & Post-Hoc Results</h2>
        <table>
            <tr><th>Statistic</th><th>p-value</th><th>Effect Size</th><th>Effect Size Type</th><th>Effect Magnitude</th></tr>
            <tr>
                <td>{safe_round(result.get('statistic'))}</td>
                <td>{safe_round(result.get('p_value'))}</td>
                <td>{safe_round(result.get('effect_size'))}</td>
                <td>{result.get('effect_size_type', 'N/A')}</td>
                <td>{result.get('effect_size_label', 'N/A')}</td>
            </tr>
        </table>
        {posthoc_html}

        <h2>6. Plain-English Interpretation & Recommendation</h2>
        <p><b>Decision:</b> {interp.get('decision', 'N/A')}</p>
        <p><b>Interpretation:</b> {interp.get('plain_english', 'N/A')}</p>
        <p><b>Operational Meaning:</b> {interp.get('operational_meaning', 'N/A')}</p>

        <div class="footer">Generated by the Statistical Intelligence Platform (SIP) — Automated Statistical Analysis and Decision Support System.</div>
    </body>
    </html>
    """
    return html


def _sanitize_for_pdf(text: str) -> str:
    """FPDF's core fonts only support latin-1; strip/replace anything outside that range."""
    return text.encode("latin-1", "replace").decode("latin-1")


def _build_pdf_report():
    df = st.session_state["df"]
    dataset_name = st.session_state.get("dataset_name", "Unknown")
    objective = st.session_state.get("analysis_objective", "N/A")
    result = st.session_state.get("test_results", {})
    recommendation = st.session_state.get("test_recommendation", {})
    interp = st.session_state.get("interpretation", {})
    homogeneity = st.session_state.get("homogeneity_results")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, _sanitize_for_pdf("SIP - Statistical Analysis Report"), ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, _sanitize_for_pdf(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}"), ln=True)
    pdf.ln(4)

    def section(title):
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(11, 61, 145)
        pdf.cell(0, 10, _sanitize_for_pdf(title), ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 10)

    def body(text):
        pdf.multi_cell(0, 6, _sanitize_for_pdf(str(text)))
        pdf.ln(1)

    section("1. Dataset Information")
    body(f"Dataset: {dataset_name} | Rows: {df.shape[0]} | Columns: {df.shape[1]}")

    section("2. Analysis Objective & Variables")
    body(f"Objective: {objective}")
    body(f"Group: {st.session_state.get('group_col', 'N/A')} | Value: {st.session_state.get('value_col', 'N/A')} | "
         f"Secondary: {st.session_state.get('value_col_2', 'N/A')}")

    section("3. Assumption Results")
    is_normal = st.session_state.get("is_normal")
    body(f"Normality assumption satisfied: {is_normal}")
    if homogeneity and homogeneity.get("p_value") is not None:
        body(f"Levene's test p-value: {safe_round(homogeneity.get('p_value'))} "
             f"(Equal variance: {homogeneity.get('equal_variance')})")

    section("4. Selected Statistical Method")
    body(f"Recommended: {recommendation.get('test', 'N/A')}")
    for r in recommendation.get("reasoning", []):
        body(f"- {r}")
    body(f"Test run: {result.get('test', 'N/A')}")

    section("5. Statistical Output")
    body(f"Statistic: {safe_round(result.get('statistic'))} | p-value: {safe_round(result.get('p_value'))}")
    body(f"Effect size ({result.get('effect_size_type', 'N/A')}): {safe_round(result.get('effect_size'))} "
         f"({result.get('effect_size_label', 'N/A')})")

    section("6. Interpretation & Recommendation")
    body(f"Decision: {interp.get('decision', 'N/A')}")
    body(f"Interpretation: {interp.get('plain_english', 'N/A')}")
    body(f"Operational Meaning: {interp.get('operational_meaning', 'N/A')}")

    return bytes(pdf.output(dest="S"))


def render_page():
    module_header("MOD_01 / M9", "Report Export", "generate a downloadable analysis report")
    st.caption("Module 9 — Generate a downloadable analysis report.")

    if not st.session_state.get("report_ready"):
        st.warning("⚠️ Please complete the Hypothesis Testing step (Page 5) first.")
        return

    st.success("✅ Analysis complete. Your report is ready to export.")

    html_report = _build_html_report()
    st.download_button(
        label="⬇️ Download HTML Report",
        data=html_report,
        file_name=f"SIP_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.html",
        mime="text/html",
    )

    try:
        pdf_bytes = _build_pdf_report()
        st.download_button(
            label="⬇️ Download PDF Report",
            data=pdf_bytes,
            file_name=f"SIP_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.pdf",
            mime="application/pdf",
        )
    except Exception as e:
        st.info(f"PDF export unavailable ({e}). Please use the HTML report instead.")

    st.divider()
    st.subheader("Report Preview")
    st.components.v1.html(html_report, height=600, scrolling=True)
